version: '3.8'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    logging: *default-logging
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
