version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html

